services:
  nginx:
    image: openquantumsafe/nginx
    ports:
      - 4433:4433
    restart: always
    environment:
      - DEFAULT_GROUPS=x25519:x448:kyber512:p256_kyber512:kyber768:p384_kyber768:kyber1024:p521_kyber1024:bikel1:bikel3:x25519_kyber768:prime256v1

  curl:
    image: openquantumsafe/curl
    command: tail -F anything

  api:
    image: qujata/api:1.0.0
    ports:
      - 3010:3010
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  pqc-portal:
    image: qujata/portal:1.0.0
    ports:
      - 8080:80
    environment:
      - PQC_PORTAL__BASE_API_URL=http://localhost:3010