apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "prometheus.fullname" . }}
  labels:
    {{- include "prometheus.labels" . | nindent 4 }}
data:
  prometheus.yml:
{{ .Files.Get "prometheus.yml" | toYaml | indent 4 }}