global:
  scrape_interval: 5s
  # scrape_timeout: 1s
  # evaluation_interval: 1s

scrape_configs:
  # - job_name: 'cadvisor'
  #   static_configs:
  #     - targets: ['qujata-cadvisor:8080']
  - job_name: 'kubernetes-cadvisor'
    kubernetes_sd_configs:
      - role: pod
    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
        action: keep
        regex: true
      - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
        action: replace
        regex: ([^:]+)(?::\d+)?;(\d+)
        replacement: $1:$2
        target_label: __address__
      - source_labels: [__meta_kubernetes_pod_name]
        action: replace
        target_label: kubernetes_pod_name

  - job_name: 'pushgateway'
    honor_labels: true
    static_configs:
      - targets: ['qujata-pushgateway:9091']

