name: Question
description: Ask a question about this project
labels: [question]
projects: "att/5"
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Provide a brief summary of your question.
      placeholder: Summarize your question in a few sentences.
    validations:
      required: true
