global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['qujata-cadvisor:8080']

  - job_name: 'pushgateway'
    honor_labels: true
    static_configs:
      - targets: ['qujata-pushgateway:9091']
