global:
  scrape_interval: 1s
  evaluation_interval: 1s

scrape_configs:
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cqujata-advisor:8080']

  - job_name: 'pushgateway'
    honor_labels: true
    static_configs:
      - targets: ['qujata-pushgateway:9091']
