{
 "title": "Qujata Analysis",
 "description": "A simple overview of the most important Docker host and container metrics. (cAdvisor/Node Exporter/Prometheus) updated from ID 893 by Thibaut Mottet",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Server CPU (%)",
   "type": "graph",
   "description": "Server CPU",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"qujata-nginx.*\"}[30s])) ",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Server Memory",
   "type": "graph",
   "description": "Server Memory",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_memory_usage_bytes{pod=~\"qujata-nginx.*\"}[30s])) ",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Client CPU (%)",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"qujata-curl.*\"}[30s]))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Client Memory",
   "type": "graph",
   "description": "Server Memory",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_memory_usage_bytes{pod=~\"qujata-curl.*\"}[30s])) ",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}