name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build the Docker image
      run: |
        REPO_NAME=$(echo $GITHUB_REPOSITORY | tr '/' '-')
        docker build ./portal --file ./portal/Dockerfile --tag $REPO_NAME:$(date +%s)
